const Constants = {
  GET_ALL_ARTICLES: 'GET_ALL_ARTICLES',
  GET_MOST_RECENT_ARTICLES: 'GET_MOST_RECENT_ARTICLES',
  GET_MOST_VIEWED_ARTICLES: 'GET_MOST_VIEWED_ARTICLES',
  ADD_VIEW_COUNT: 'ADD_VIEW_COUNT',
  GET_ARTICLES_LOADING: 'GET_ARTICLES_LOADING',
  GET_ARTICLES_ERROR: 'GET_ARTICLES_ERROR',
  GET_ARTICLES_QUERY: 'GET_ARTICLES_QUERY',
  RESET_ARTICLES: 'RESET_ARTICLES',
  UPDATE_OFFSET: 'UPDATE_OFFSET',
  SHOW_DISCOVER: 'SHOW_DISCOVER',
};

export default Constants;